/*
//最后整理时间：2012-06-24
//编辑者：李昂
//说明：
//   只是列举了所有的枚举变量，而具体的用法参加各类的头文件说明
*/
#ifndef _SGSDATA_ENUM_H
#define _SGSDATA_ENUM_H
#include "chain.h"
 
namespace sgs{
	namespace ConstData{
		enum CardType{//游戏牌类型
			ctNone = 0, HUOSHA, LEISHA, SHA, SHAN, TAO, JIU, //基本牌
            CHITU = 10, DAWAN, ZICI, //减一马
            DILU = 15, JUEYING, ZHUAHUANG, HUALIU,//加一马
            BAIYIN = 20, TENGJIA, BAGUA, RENWANG, //防具
            ZHUGE = 30, QINGGANG, HANBING, CIXIONG, GUANSHI, YINYUE, QINGLONG, GUDING, ZHANGBA, FANGTIAN, QILIN, ZHUQUE, //武器
            BINGLIANG = 50, SISHU, SHANDIAN, //延时锦囊
            GUOCHAI = 60, HUOGONG, JIEDAO, JUEDOU, NANMAN, SHUNQIAN, TAOYUAN, TIESUO, WANJIAN, WUXIE, WUZHONG, WUGU//非延时锦囊
		};
        enum CardColor{ccNone = 0, HEART, SPADE, DIAMOND, CLUB};//卡牌花色

		enum HeroSide{hsNone = 0, WEI, SHU, WU, QUN};//势力
		enum HeroSex{hxNone = 0, MALE,FEMALE};//性别
		enum HeroType{//武将
			htNone = 0,  SUJIANG, NVSUJIANG,
			CAOCAO, SIMAYI, XIAHOUDUN, ZHANGLIAO, XUCHU, GUOJIA, ZHENJI, XIAHOUYUAN, ZHANGHE, XUHUANG, CAOREN, DIAWEI, XUNYU, CAOPI, DENGAI, CAOZHI, XUSHU, YUJIN, ZHANGCHUNHUA, YANGXIU,
            LIUBEI, GUANYU, ZHANGFEI, LAOZHUGE, ZHAOYUN, MACHAO, HUANGYUEYING, HUANGZHONG, WEIYAN, PANGTONG, HUOZHUGE, JIANGWEI, LIUSHAN, MENGHUO, ZHURONG, FAZHENG, MASU,
			SUNQUAN, GANNING, LVMENG, HUANGGAI, ZHOUYU, DAQIAO, LUXUN, SUNSHANGXIANG, SUNJIAN, SUNCE, XIAOQIAO, TAISHICI, ZHOUTAI, LUSU, ZHANGZHAO, LINGTONG, WUGUOTAI, XUSHENG,
			HUATUO, LVBU, DIAOCHAN, YUANSHAO, YANLIANG, DONGZHUO, JIAXU, PANGDE, ZUOCI, ZHANGJIAO, YUJI, CAIWENJI, CHENGONG, GAOSHUN, GONGSUNZAN, YUANSHU
		};
		enum HeroSkill{//技能
			hkNone = 0,JIANXIONG, HUJIA, FANKUI, GUICAI, GANGLIE, TUXI, LUOYI, TIANDU, YIJI, QINGGUO, LUOSHEN, SHENSU, QIAOBIAN, DUANLIANG, JUSHOU, QIANGXI, QUHU, JIEMING, XINGSHANG, FANGZHU, SONGWEI, TUNTIAN, JIANXIAN, LUOYING, JIUSHI, WUYAN, JUJIAN, YIZHONG, JUEQING, SHANGSHI, DANLUO, JILEI,
			RENDE, JIJIANG, WUSHENG, PAOXIAO, GUANXING, KONGCHENG, LONGDAN, MASHU, TIEQI, JIZHI, QICAI, LIEGONG, KUANGGU, LIANHUAN, NIEPAN, BAZHEN, HUOJI, KANPO, TIAOXIN, ZHIJI, XIANGLE, FANGQUAN, RUOYU, HUOSHOU, ZAIQI, JUXIANG, LIEREN, ENYUAN, XUANHUO, XINZHAN, HUILEI,
			ZHIHENG, JIUYUAN, QIXI, KEJI, KUROU, YINGZI, FANJIAN, GUOSE, LIULI, QIANXUN, LIANYING, JIEYIN, XIAOJI, YINGHUN, JIANG, HUNZI, ZHIBA, TIANXIANG, HONGYAN, TIANYI, BUQU, HAOSHI, DIMENG, ZHIJIAN, GUZHENG, XUANFENG, GANLU, BUYI, POJUN,
			JIJIU, QINGNANG, WUSHUANG, LIJIAN, BIYUE, LUANJI, XUEYI, SHUANGXIONG, JIUCHI, ROULIN, BENGHUAI, BAONUE, WANSHA, LUANWU, WEIMU, MENGJIN, HUASHEN, XINSHENG, LEIJI, GUIDAO,HUANGTIAN, GUHUO, BEIGE, DUANCHANG, MINGCE, ZHICHI, XIANZHEN, JINJIU, YICONG, YONGSI, WEIDI
		};

		enum PlayerRole{prNone = 0, ZHU, ZHONG, FAN, NEI};//身份
		enum PlayerPhase{ppNone = 0, START, JUDGEMENT, GETCARD, MAIN, ABANDONCARD, END, OTHER};//阶段
		enum PlayerStatus{psNone = 0, SkillOneUsed = 1, SkillTwoUsed = 2, ATTACKED = 4, LE = 8, BING = 16, DEAD = 32};//状态

		enum MessageType{mtNone = 0, USECARD, HITCARD, USESKILL,JUDGE, HURT, TRANSCARD, SWITCHPHASE, DYING, KILL, ERROR, BEGIN, FINALE};//消息标记，HURT包括回血，TRANSCARD指卡牌转移（从玩家到牌堆、玩家到玩家、场上到玩家等），begin用于标记一个连锁相应的开始。
		//enum TransType{trNone = 0,POOLTOP,POOLBOTTOM,DUSTBIN,PLAYERS,DESKTOP};
		enum ErrorType{etNone = 0,OPERATION/*,OVERFLOW,HOP*/};//错误讯息：溢出，操作错误，在一个指令收集的过程中得到了不相干的指令导致退出

		enum RegionType{rtNone = 0, HAND, EQUIP, SKILL, PLAYER, WINDOW, SYSTEM, DEFAULT, DESK, POOLTOP, POOLBOTTOM, DUST};//区域标记，SYSTEM中包括确定（1），取消（0），弃牌（2）
        enum PlayerRegionType{prtNone = 0, PHAND, PEQUIP, PJUDGE};//玩家的区域
	}
}
 
#endif /*_SGSDATA_ENUM_H*/
